name: onedrive_api
description: A Dart client for the OneDrive API that provides easy access to OneDrive's file operations including upload, download, copy, move, and more.
version: 0.0.2



resolution: workspace 

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  oauth2restclient:
    path: ../oauth2restclient
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
#flutter: 