name: yandex_drive_api_example
description: "Example app for yandex_drive_api package."
version: 1.0.0

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  yandex_drive_api:
    path: ../
  dotenv: ^4.2.0
  file_picker: ^10.3.7
  http: ^1.2.0
  path_provider: ^2.1.3
      

  oauth2restclient:
    path: ../../../packages/oauth2restclient


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true